jabardigitalservice/dedi-core-service

.eslintrc.json
.github/workflows/CI.yml
docker-compose-dev.yml
docker-compose.yml
package-lock.json
package.json
src/database/migrations/20211008031514_categories.ts
src/database/migrations/20211008032602_partners.ts
src/database/migrations/20211008033154_areas.ts
src/database/migrations/20211008033500_cities.ts
src/database/migrations/20211008033943_districts.ts
src/database/migrations/20211008034146_villages.ts
src/helpers/_test.ts
src/helpers/test/_test.ts
src/helpers/test/example.ts
src/jest.config.ts

- setup docker config
- add migrations
- title: setup docker, migrations desa digital
- participants: @ayocodingit @firmanJS @rizkyrmsyah @setiadijoe @sandisunandar99

setup docker, migrations

---

package-lock.json
package.json
src/modules/villages/village_entity.ts
src/modules/villages/village_handler.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_rules.ts
src/modules/villages/village_service.ts
src/modules/villages/village_test.ts
src/server.ts

- add village with location (module village)
Related: https://airtable.com/appdN4AdnU8FNs94M/tblRtWbyq60Fx1m6v/viwz1FKMjbiJpUkeB/rec6Qf99mDjjpiaaI?blocks=hide
Next Todo: 
- improve redis for maps locations
- title: add village with location (module village) peta sebaran desa digital 
- participants: @ayocodingit @firmanJS @sandisunandar99 @tukangremot @setiadijoe @rachadiannovansyah

module village with location

---

src/modules/partners/partner_repository.ts

- add response website
- title: add response website module partner
- participants: @ayocodingit @tukangremot @rizkyrmsyah @indraprasetya154 @setiadijoe

add response website module partner

---

src/modules/testimonials/testimonial_entity.ts
src/modules/testimonials/testimonial_handler.ts
src/modules/testimonials/testimonial_repository.ts
src/modules/testimonials/testimonial_service.ts
src/modules/testimonials/testimonial_test.ts
src/server.ts

-> GET /v1/testimonials 
[Related](https://airtable.com/appdN4AdnU8FNs94M/tblRtWbyq60Fx1m6v/viwz1FKMjbiJpUkeB/recGTZr3LJTywmU5l?blocks=hide)
CC: @jabardigitalservice/jds-backend 
- title: Membuat module testimonial
- participants:  @ayocodingit @tukangremot @firmanJS

Module testimonial

---

src/modules/partners/partner_entity.ts
src/modules/partners/partner_handler.ts
src/modules/partners/partner_repository.ts
src/modules/partners/partner_service.ts
src/modules/partners/partner_test.ts
src/modules/villages/village_entity.ts
src/modules/villages/village_handler.ts
src/modules/villages/village_service.ts
src/modules/villages/village_test.ts

- module villages with location
- module partners
- title: standarisasi response meta data
- participants: @ayocodingit @azophy

improve response meta data

---

src/modules/testimonials/testimonial_entity.ts
src/modules/testimonials/testimonial_handler.ts
src/modules/testimonials/testimonial_service.ts
src/modules/testimonials/testimonial_test.ts

- title: Add metadata in list testimonials response 
- participants:  @ayocodingit @tukangremot @firmanJS

Add meta data

---

src/modules/partners/partner_handler.ts
src/modules/villages/village_handler.ts

- update handler partners
- update handler villages
- title: standard handler partners villages
- participants: @ayocodingit @firmanJS

standard handler partners villages

---

src/modules/villages/village_entity.ts
src/modules/villages/village_handler.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_service.ts
src/modules/villages/village_test.ts

- title: Implement get village detail by id
- participants: @ayocodingit @firmanJS @tukangremot

feat(village): implement get village detail by id

---

src/helpers/mail.ts

- update mail set name sender email
- title: update mail set name sender email
- participants: @ayocodingit @firmanJS @firmanhxc @sandisunandar99 @rachadiannovansyah

update mail set name sender email

---

src/modules/villages/village_entity.ts
src/modules/villages/village_handler.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_service.ts
src/modules/villages/village_test.ts

- remove unused suggestion search village
- title: remove unused endpoint suggestion search village
- participants: @ayocodingit @setiadijoe @khihadysucahyo @rachadiannovansyah 

sprint 2 remove unused suggestion search village

---

src/database/migrations/20211016232523_create_table_testimonials.ts
src/database/seeds/testimonials.ts
src/modules/testimonials/testimonial_entity.ts
src/modules/testimonials/testimonial_repository.ts
src/modules/testimonials/testimonial_service.ts
src/modules/testimonials/testimonial_test.ts

- modify table testimonials based on the picture above,
- modify testimonial seeder,
- modify testimonial test, entity, repository, and service.
cc. @jabardigitalservice/jds-backend 
- title: update module testimonials
- participants:  @ayocodingit @sandisunandar99

update module testimonials based on new structure

---

.codeclimate.yml
.eslintrc.json
src/config/jest.ts
src/modules/partners/partner_entity.ts
src/modules/partners/partner_handler.ts
src/modules/partners/partner_repository.ts
src/modules/partners/partner_service.ts
src/modules/partners/partner_test.ts

- title: create partner suggestion endpoint
- participants:  @firmanJS @sandisunandar99 @ayocodingit

feat(partner): create partner suggestion endpoint

---

src/database/migrations/20211018084932_create_table_users.ts

- update table users
- title: sprint 2 update table users 
- participants: @ayocodingit @rindibudiaramdhan @firmanJS 

Sprint 2 update table users

---

src/lang/locales/id.json
src/modules/auth/auth_service.ts

result: 
figma: 
- title: memperbaiki redaksi email forgot password
- participants: @ayocodingit @rachadiannovansyah @firmanJS @khihadysucahyo

Sprint 2/modify redaction validation template email

---

src/modules/testimonials/testimonial_repository.ts
src/modules/testimonials/testimonial_test.ts

- Update SQL query with adding where clause is active true, to find all only active data
- Modify test sentence
title: fix SQL query to find all testimonials data
project: Desa Digital
participants:  @ayocodingit

update query to select active data

---

src/modules/partners/partner_repository.ts
src/modules/partners/partner_service.ts

- improve query last update partner
- title: improve query last update partner
- participants: @ayocodingit @rachadiannovansyah @sandisunandar99 @firmanJS @rindibudiaramdhan

improve: query last update partner

---

.eslintrc.json
src/database/seeds/testimonials.ts

fix seed testimonials

---

src/database/migrations/20211008034146_create_table_villages.ts
src/modules/testimonials/testimonial_service.ts
src/modules/villages/village_entity.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_service.ts

- add meta last update list villages
- testimonial: modify find All Using Cursor
- participants: @ayocodingit @sandisunandar99 @setiadijoe @tukangremot 
- title: Menambahkan Meta Last Update pada list Villages

Sprint 2/add meta last update list villages

---

.github/workflows/dedi-service-release-staging.yml
docker/Dockerfile

- add continues deployment release staging
project: Desa Digital
title: menambahkan continuous deployment dengan github action
participants: @ayocodingit @firmanJS @rindibudiaramdhan @setiadijoe @rachadiannovansyah @sandisunandar99

add release staging

---

package-lock.json
package.json
src/database/seeds/testimonials.ts
src/modules/partners/partner_test.ts
src/modules/testimonials/testimonial_test.ts

- update seeder testimonials
- update test partners
- update test testimonials
- title: improve date to momentjs
- participants: @ayocodingit @firmanJS @sandisunandar99 @rindibudiaramdhan @setiadijoe @tukangremot

improve date to momentjs

---

src/modules/villages/village_repository.ts
src/modules/villages/village_service.ts

- modify meta total on find all villages
- title: villages find all fixing meta total last update
- participants: @ayocodingit @firmanJS @setiadijoe

villages: find all fixing meta total last update

---

src/lang/locales/id.json
src/modules/auth/auth_service.ts

- modify response signin on failed
- participants: @ayocodingit @indraprasetya154 @sandisunandar99 
- title: modify response signin on failed

modify response signin on failed

---

src/helpers/validator.ts
src/lang/locales/id.json
src/modules/auth/auth_rules.ts

- add lang rule validate min max
- add password rule min length 6 character
- participants: @ayocodingit @sandisunandar99 @indraprasetya154 @rachadiannovansyah 
- title: add rule validate min max ( case min password length 6 character)

add rule validate min max

---

src/database/migrations/20211008033500_create_table_cities.ts
src/modules/cities/city_entity.ts
src/modules/cities/city_handler.ts
src/modules/cities/city_log.ts
src/modules/cities/city_repository.ts
src/modules/cities/city_rules.ts
src/modules/cities/city_service.ts
src/modules/cities/city_test.ts
src/server.ts

- add endpoint cities list with location
the goal is bounds to get a city marker
- title: add endpoint cities list with location
- participants: @ayocodingit @firmanJS @setiadijoe

add endpoint cities list with location

---

src/modules/villages/village_entity.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_service.ts

- add meta pagination without query bounds
- title: add meta pagination without query bounds
- participants: @ayocodingit @tukangremot @sandisunandar99

villages: add meta pagination without query bounds

---

src/modules/villages/village_entity.ts
src/modules/villages/village_handler.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_service.ts
src/modules/villages/village_test.ts

- purpose: get data village with location villages 
- limit: bounds maps
- purpose: get data village with location villages 
- limit: pagination 
- add endpoint `/v1/villages/with-location` 
- add endpoint `/v1/villages/list-with-location`
- title: memisahkan endpoint untuk list pagination dan list bounds (module Villages)
- participants: @ayocodingit @tukangremot @sandisunandar99 @rindibudiaramdhan @setiadijoe

separate endpoints for list pagination and list bounds (module Villages)

---

README.md

- Update readme.md
- title: modify readme.md to fit current situation
- participants:  @ayocodingit @firmanJS

docs(readme): modify readme to fit current situation

---

src/database/seeds/partners.ts

- Create seeder for partners
- title: Add partners seeder
- projects: Desa Digital
- participants:  @ayocodingit

Sprint 3/partners seeder

---

src/database/migrations/20211008032602_create_table_partners.ts
src/database/migrations/20211016232523_create_table_testimonials.ts
src/modules/partners/partner_entity.ts
src/modules/partners/partner_handler.ts
src/modules/partners/partner_repository.ts
src/modules/partners/partner_service.ts
src/modules/partners/partner_test.ts
src/modules/testimonials/testimonial_entity.ts
src/modules/testimonials/testimonial_handler.ts
src/modules/testimonials/testimonial_repository.ts
src/modules/testimonials/testimonial_service.ts
src/modules/testimonials/testimonial_test.ts

- remove query cursor prepare for CMS
- title: Remove research (Query cursor) prepare for CMS
- participants: @ayocodingit @tukangremot @rachadiannovansyah

Remove research (Query cursor) prepare for CMS

---

src/modules/partners/partner_handler.ts
src/modules/partners/partner_rules.ts

- fix: remove rules find all (module partner)
- title: fix: remove rules find all (module partner)
- participants: @ayocodingit @firmanJS @sandisunandar99 @rindibudiaramdhan @rachadiannovansyah

fix: remove rules find all

---

README.md
src/helpers/validator.ts
src/modules/auth/auth_handler.ts
src/modules/auth/auth_http.ts
src/server.ts

- separate handler with http
- auth: update design pattern
cc: @jabardigitalservice/jds-backend @firmanJS @sandisunandar99 
- title: auth: update design pattern
- participants: @ayocodingit @firmanJS @tukangremot @rizkyrmsyah @sandisunandar99

auth: update design pattern

---

src/modules/partners/partner_handler.ts
src/modules/partners/partner_http.ts
src/server.ts

- Separate routes and handler functions into their own files
- title: refactor(partner): separate routes and handler functions
- participants:  @firmanJS @tukangremot @ayocodingit

refactor(partner): separate routes and handler functions

---

package-lock.json
package.json
src/helpers/roles.ts
src/lang/locales/id.json
src/middleware/grantAccess.ts

- helpers: role base access controll
- title: menambahkan helpers role base access control
- participants: @ayocodingit @rachadiannovansyah @firmanJS @tukangremot @sandisunandar99

helpers: role base access controll

---

src/modules/auth/auth_entity.ts
src/modules/auth/auth_service.ts

- add condition is admin on signup
- title: add condition is admin on signup
- participants: @ayocodingit @tukangremot @rindibudiaramdhan @rachadiannovansyah @sandisunandar99 @firmanJS

add condition is admin on signup

---

src/modules/auth/auth_handler.ts
src/modules/auth/auth_http.ts
src/modules/auth/auth_service.ts

- feat: sign out
endpoint: `/v1/auth/users/sign-out`
- title: membuat endpoint sign out
- participants: @ayocodingit @tukangremot @sandisunandar99 @indraprasetya154

feat: sign out

---

src/modules/files/file_entity.ts
src/modules/files/file_handler.ts
src/modules/pages/page_entity.ts
src/modules/pages/page_handler.ts
src/modules/pages/page_http.ts
src/modules/pages/page_repository.ts
src/modules/pages/page_service.ts

- feat: add endpoint find by id (pages)
- modify response upload file
- title: feat: add endpoint find by id (pages)
- participants: @ayocodingit @tukangremot @sandisunandar99 @rindibudiaramdhan

feat: add endpoint find by id (pages)

---

src/modules/pages/page_access.ts
src/modules/pages/page_entity.ts
src/modules/pages/page_handler.ts
src/modules/pages/page_http.ts
src/modules/pages/page_repository.ts
src/modules/pages/page_rules.ts
src/modules/pages/page_service.ts

- feat: add endpoint store (pages)
- title: feat: add endpoint store (pages)
- participants: @ayocodingit @sandisunandar99 @firmanJS @tukangremot

feat: add endpoint store (pages)

---

src/helpers/s3.ts
src/modules/files/file_handler.ts
src/modules/pages/page_access.ts
src/modules/pages/page_entity.ts
src/modules/pages/page_handler.ts
src/modules/pages/page_http.ts
src/modules/pages/page_repository.ts
src/modules/pages/page_service.ts

- feat: add endpoint destroy (pages)
- feat: modify store is active (pages)
cc: @jabardigitalservice/jds-backend @sandisunandar99
- title: feat: add endpoint destroy (pages)
- participants: @ayocodingit @sandisunandar99 @tukangremot @rindibudiaramdhan @rachadiannovansyah

feat: add endpoint destroy (pages)

---

src/modules/pages/page_access.ts
src/modules/pages/page_entity.ts
src/modules/pages/page_handler.ts
src/modules/pages/page_http.ts
src/modules/pages/page_repository.ts
src/modules/pages/page_rules.ts
src/modules/pages/page_service.ts

- feat: add endpoint update (pages)
- title: feat: add endpoint update (pages)

feat: add endpoint update (pages)

---

jest.config.ts
src/modules/pages/page_handler.ts
src/modules/pages/page_service.ts
src/modules/pages/page_test.ts

- feat: add api test (pages)
- title: feat: add api test (pages)
- participants: @ayocodingit @sandisunandar99 @rizkyrmsyah @rachadiannovansyah

feat: add api test (pages)

---

src/database/migrations/20211018084932_create_table_users.ts
src/lang/locales/id.json
src/modules/auth/auth_entity.ts
src/modules/auth/auth_rules.ts
src/modules/auth/auth_service.ts
src/modules/pages/page_rules.ts

- add field is active table users
- modify rules auth 
- title: add field is active table users
- participants: @ayocodingit @tukangremot @rachadiannovansyah @rizkyrmsyah @sandisunandar99

add field is active table users

---

src/modules/villages/village_service.ts
src/modules/villages/village_test.ts

- modify: update api test villages
before: 
after:
- title: modify: update api test villages
- participants: @ayocodingit @firmanJS @rachadiannovansyah

modify: update api test villages

---

src/helpers/constant.ts
src/modules/pages/page_entity.ts
src/modules/pages/page_test.ts
src/modules/villages/village_service.ts
src/modules/villages/village_test.ts

- update test pages
- update test villages

update: test page-village

---

src/modules/partners/partner_repository.ts
src/modules/partners/partner_service.ts
src/modules/partners/partner_test.ts
src/modules/villages/village_test.ts

- feat: api test modules partners
before:
after:

feat: api test modules partners

---

src/lang/locales/id.json
src/modules/auth/auth_http.ts

- feat: auth sign in limit response
- response error will be concat with countdown time
- title: feat: auth sign in limit response
- participants: @ayocodingit @rizkyrmsyah @sandisunandar99 @indraprasetya154

feat: auth sign in limit response

---

src/database/migrations/20211016232523_create_table_testimonials.ts
src/database/migrations/20211221034605_create_table_pages.ts
src/modules/pages/page_entity.ts
src/modules/pages/page_repository.ts
src/modules/pages/page_rules.ts
src/modules/pages/page_service.ts
src/modules/pages/page_test.ts

- update table page
- change field description to link (pages)
Reference: 
cc: @jabardigitalservice/jds-backend @tukangremot @sandisunandar99 
- title: feat: modify field description to link (pages)

feat: modify field description to link (pages)

---

src/database/migrations/20211016232523_create_table_testimonials.ts
src/modules/testimonials/testimonial_entity.ts
src/modules/testimonials/testimonial_http.ts
src/modules/testimonials/testimonial_repository.ts
src/modules/testimonials/testimonial_rules.ts
src/modules/testimonials/testimonial_service.ts
src/modules/testimonials/testimonial_test.ts

- feat: modify find all (testimonial)
- add field partner_id (Required if type testimonial `mitra`)
- add field village_id (Required if type testimonial `masyarakat`)
- changes response data with added object village and object partner
cc: @jabardigitalservice/jds-backend @tukangremot @sandisunandar99 
- title: feat: modify find all (testimonial)
- participants: @ayocodingit @indraprasetya154 @rizkyrmsyah @rindibudiaramdhan @sandisunandar99 @rachadiannovansyah @tukangremot

feat: modify find all (testimonial) 

---

src/modules/districts/district_repository.ts
src/modules/districts/district_service.ts
src/modules/pages/page_repository.ts
src/modules/pages/page_service.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_service.ts

- modify: use singular variable each query join
- title: modify: use singular variable each query join
- participants: @ayocodingit @rizkyrmsyah @tukangremot @indraprasetya154 @rindibudiaramdhan @sandisunandar99

modify: use singular variable each query join

---

src/helpers/validator.ts
src/modules/testimonials/testimonial_access.ts
src/modules/testimonials/testimonial_entity.ts
src/modules/testimonials/testimonial_handler.ts
src/modules/testimonials/testimonial_http.ts
src/modules/testimonials/testimonial_repository.ts
src/modules/testimonials/testimonial_rules.ts
src/modules/testimonials/testimonial_service.ts
src/modules/testimonials/testimonial_test.ts

- feat: create testimonial
- add endpoint `POST` `/v1/testimonials`
- add api test store with type role 1 `(mitra)`
- if role as `mitra` field partner_id is required
- add api test store with type role 2 `(masyarakat)`
- if role as `masyarakat` field village_id is required
- title: feat: add endpoint create testimonial
- participants: @ayocodingit @rizkyrmsyah @rindibudiaramdhan @rachadiannovansyah @indraprasetya154

feat: add endpoint create testimonial

---

src/modules/testimonials/testimonial_access.ts
src/modules/testimonials/testimonial_entity.ts
src/modules/testimonials/testimonial_handler.ts
src/modules/testimonials/testimonial_http.ts
src/modules/testimonials/testimonial_repository.ts
src/modules/testimonials/testimonial_rules.ts
src/modules/testimonials/testimonial_service.ts
src/modules/testimonials/testimonial_test.ts

- add endpoint find by id (testimonial)
- add endpoint destroy (testimonial)
cc: @jabardigitalservice/jds-backend @tukangremot @sandisunandar99 
- title: feat: add endpoint find by id & endpoint destroy (testimonial)
- participants: @ayocodingit @rizkyrmsyah @rindibudiaramdhan @indraprasetya154 @samudra-ajri @sandisunandar99

feat: add endpoint find by id & endpoint destroy (testimonial)

---

src/modules/testimonials/testimonial_access.ts
src/modules/testimonials/testimonial_entity.ts
src/modules/testimonials/testimonial_handler.ts
src/modules/testimonials/testimonial_http.ts
src/modules/testimonials/testimonial_repository.ts
src/modules/testimonials/testimonial_rules.ts
src/modules/testimonials/testimonial_service.ts
src/modules/testimonials/testimonial_test.ts

- add endpoint find by id (testimonial)
- add endpoint destroy (testimonial)
cc: @jabardigitalservice/jds-backend @tukangremot @sandisunandar99 
- title: feat: add endpoint find by id & endpoint destroy (testimonial)
- participants: @ayocodingit @sandisunandar99 @rindibudiaramdhan @indraprasetya154

feat: add endpoint update (testimonial)

---

src/modules/pages/page_repository.ts
src/modules/pages/page_rules.ts

- modify: change default order by updated at sort desc
- title: modify: change default order by updated at sort desc (pages)
- participants: @ayocodingit @rindibudiaramdhan @rachadiannovansyah @sandisunandar99 @indraprasetya154

modify: change default order by updated at sort desc

---

src/modules/pages/page_entity.ts
src/modules/pages/page_repository.ts
src/modules/pages/page_service.ts
src/modules/pages/page_test.ts

- feat: add field order list (pages)

feat: add field order list (pages)

---

src/modules/pages/page_rules.ts
src/modules/pages/page_test.ts
src/modules/testimonials/testimonial_rules.ts
src/modules/testimonials/testimonial_test.ts

- fix: upload file must be unique source file
- issue duplicate when input filename exists
- title: fix: upload file must be unique source file 
- participants: @ayocodingit @indraprasetya154 @azophy @rindibudiaramdhan @sandisunandar99

fix: upload file must be unique source file

---

docker/Dockerfile

- fix: add platform linux/amd64 (issue M1 chips)
- participants: @ayocodingit @indraprasetya154 @rachadiannovansyah 
- title: Fix: add platform linux/amd64 (issue M1 chips)

fix: add platform linux/amd64 (issue M1 chips)

---

src/modules/villages/village_entity.ts
src/modules/villages/village_handler.ts
src/modules/villages/village_http.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_service.ts

- feat: add endpoint suggestion villages
- title: feat: add endpoint suggestion villages

feat: add endpoint suggestion villages

---

src/database/migrations/20211008034146_create_table_villages.ts
src/modules/villages/village_test.ts

- feat: add api test village suggestion
- modify length id villages to 14 character
- title: feat: add api test village suggestion
- participants: @ayocodingit @rachadiannovansyah @sandisunandar99 @indraprasetya154 @tukangremot

feat: add api test village suggestion

---

src/modules/testimonials/testimonial_entity.ts
src/modules/testimonials/testimonial_repository.ts
src/modules/testimonials/testimonial_service.ts

- feat: add response is active list **testimonial**
- feat: add search list **testimonial**
- title: feat: add response is active list (testimonial)
- participants: @ayocodingit @indraprasetya154 @firmanhxc @rachadiannovansyah

feat: add response is active list

---

src/modules/partners/partner_handler.ts
src/modules/partners/partner_http.ts
src/modules/partners/partner_repository.ts
src/modules/partners/partner_service.ts
src/modules/partners/partner_test.ts
src/modules/testimonials/testimonial_repository.ts
src/modules/testimonials/testimonial_rules.ts

- fixing: remove min 3 char search by name
- update list sorting default by created_at desc
- title: fixing: remove min 3 char search by name (Partners)
- participants: @ayocodingit @sandisunandar99 @rindibudiaramdhan

fixing: remove min 3 char search by name

---

src/database/migrations/20211018084932_create_table_users.ts
src/helpers/gcs.ts
src/modules/users/user_access.ts
src/modules/users/user_entity.ts
src/modules/users/user_handler.ts
src/modules/users/user_http.ts
src/modules/users/user_log.ts
src/modules/users/user_repository.ts
src/modules/users/user_rules.ts
src/modules/users/user_service.ts
src/server.ts

- feat: add endpoint list and view (users)
- add field updated_at and last_login_at
ref: 
response API: 
- title:  feat: add endpoint list and view (users)
- participants: @ayocodingit

feat: add endpoint list and view (users)

---

src/modules/users/user_handler.ts
src/modules/users/user_http.ts
src/modules/users/user_repository.ts
src/modules/users/user_service.ts

- feat: add endpoint destroy users
- title: feat: add endpoint destroy users
- participants: @ayocodingit @rachadiannovansyah @khihadysucahyo @bangunbagustapa

feat: add endpoint destroy users

---

src/modules/auth/auth_entity.ts
src/modules/auth/auth_repository.ts
src/modules/auth/auth_service.ts

- update last login at each sign in
- title: update last login at each sign in
- participants: @ayocodingit @indraprasetya154 @sandisunandar99 @rachadiannovansyah

update last login at each sign in

---

src/helpers/passwordHash.ts
src/modules/users/user_entity.ts
src/modules/users/user_handler.ts
src/modules/users/user_http.ts
src/modules/users/user_repository.ts
src/modules/users/user_rules.ts
src/modules/users/user_service.ts

- feat: add endpoint store users
- title: feat: add endpoint store users
- participants: @ayocodingit @rindibudiaramdhan  @rachadiannovansyah @sandisunandar99

feat: add endpoint store users

---

src/modules/users/user_handler.ts
src/modules/users/user_http.ts
src/modules/users/user_repository.ts
src/modules/users/user_rules.ts
src/modules/users/user_service.ts

- feat: add endpoint update users
- title: feat: add endpoint update users
- participants: @ayocodingit @rindibudiaramdhan  @rachadiannovansyah @sandisunandar99 
@indraprasetya154

feat: add endpoint update users

---

src/modules/users/user_test.ts

- feat: api test find all dan store api (users)
- title: feat: api test find all dan store api (users)
- participants: @ayocodingit @rindibudiaramdhan  @rachadiannovansyah @sandisunandar99 
@indraprasetya154

feat: api test find all dan store api (users)

---

src/modules/users/user_http.ts
src/modules/users/user_test.ts

- feat: api test find by id (users)
- title: feat: api test find by id (users)
- participants: @ayocodingit @samudra-ajri @rizkyrmsyah 
@indraprasetya154

feat: api test find by id (users)

---

jest.config.ts
src/modules/pages/page_repository.ts
src/modules/testimonials/testimonial_repository.ts
src/modules/testimonials/testimonial_test.ts
src/modules/users/user_handler.ts
src/modules/users/user_repository.ts
src/modules/users/user_test.ts
src/modules/villages/village_handler.ts
src/modules/villages/village_test.ts

- [feat: add api test update & destroy (users)](https://github.com/jabardigitalservice/dedi-core-service/commit/e0ab85e03357cdafc21d50057b2987bc3f80e805)
- [complete test coverage](https://github.com/jabardigitalservice/dedi-core-service/commit/71e518fa208f822dfc3db2422cf4e2d148a1048e)
- title: feat: add api test update & destroy (users)
- participants: @ayocodingit @rindibudiaramdhan @sandisunandar99 @indraprasetya154

Feat/api test/update & destroy

---

src/database/migrations/20211221035316_create_table_files.ts

- feat: add unique in field source (files)
- title: feat: add unique in field source (files)
- participants: @ayocodingit @indraprasetya154 @rachadiannovansyah @sandisunandar99

feat: add unique in field source (files)

---

src/modules/users/user_entity.ts
src/modules/users/user_rules.ts
src/modules/users/user_service.ts
src/modules/users/user_test.ts

- modify: remove field unused password_confirm & is_active (users)
- title: modify: remove field unused password_confirm & is_active (users)
- participants: @ayocodingit @sandisunandar99 @rizkyrmsyah @indraprasetya154

modify: remove field unused password_confirm & is_active

---

src/modules/users/user_access.ts
src/modules/users/user_entity.ts
src/modules/users/user_handler.ts
src/modules/users/user_http.ts
src/modules/users/user_repository.ts
src/modules/users/user_rules.ts
src/modules/users/user_service.ts
src/modules/users/user_test.ts

- feat: add endpoint update status (users)
- title: feat: add endpoint update status (users)

feat: add endpoint change status (users)

---

.env.example
src/config/cors.ts
src/lang/locales/id.json
src/middleware/verifyPublic.ts
src/modules/files/file_http.ts
src/server.ts

- feat: add verify public on upload file
- title: feat: add verify public on upload file
- participants: @ayocodingit @sandisunandar99 @indraprasetya154 @rachadiannovansyah

feat: add verify public on upload file

---

src/modules/users/user_rules.ts
src/modules/users/user_test.ts

- modify: update rule password store (users)
- title: modify: update rule password store (users)

modify: update rule password store (users)

---

src/config/cors.ts
src/modules/testimonials/testimonial_service.ts

- add convert to boolean list (testimonials)
- title: add convert to boolean list (testimonials)

add convert to boolean list (testimonials)

---

src/database/migrations/20211008034146_create_table_villages.ts
src/lang/locales/id.json
src/modules/auth/auth_rules.ts
src/modules/villages/village_entity.ts
src/modules/villages/village_handler.ts
src/modules/villages/village_http.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_rules.ts
src/modules/villages/village_service.ts
src/modules/villages/village_test.ts

- feat: add endpoint questionnaire (villages)
- title: feat: add endpoint questionnaire (villages)

feat: add endpoint questionnaire (villages)

---

src/modules/users/user_rules.ts

- fixing: validation with db field email unique
- title: fixing: validation with db field email unique
- participants: @ayocodingit @rindibudiaramdhan @indraprasetya154 @sandisunandar99

fixing: validation with db field email unique

---

src/helpers/validator.ts
src/lang/locales/id.json
src/modules/villages/village_rules.ts
src/modules/villages/village_test.ts

- feat: add validation questionnaire
- title: feat: add validation questionnaire
- participants: @ayocodingit @sandisunandar99 @indraprasetya154

feat: add validation questionnaire

---

src/config/cache.ts
src/modules/villages/village_entity.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_service.ts
src/modules/villages/village_test.ts

- feat: add condition where is active
- title: feat: add condition where is active
- participants: @ayocodingit @sandisunandar99 @fajarhikmal214 @imamdev93

feat: add condition where is active

---

.github/workflows/dedi-service-release-tags.yml

- add workflows event realase tags
- title: deploy: add workflows event realase tags
- participants: @ayocodingit @sandisunandar99 @indraprasetya154

add workflows event realase tags

---

src/knexfile.ts
src/modules/villages/village_handler.ts
src/modules/villages/village_service.ts
src/modules/villages/village_test.ts

- modify: remove validate is active questionnaire
- add interface Knex Config
- title: modify: remove validate is active questionnaire 
- participants: @ayocodingit @indraprasetya154 @sandisunandar99

modify: remove validate is active questionnaire

---

src/lang/locales/id.json
src/modules/villages/village_rules.ts

- add rule array string required (questionnaire)
- title: add rule array string required (questionnaire)
- participants: @ayocodingit @rachadiannovansyah

add rule array string required

---

.github/workflows/dedi-service-release-staging.yml

- add setup build caprover
- title: deploy: add setup build caprover (staging)
- participants: @ayocodingit @feriahmad

add setup build caprover

---

src/modules/villages/village_rules.ts

- fixing: remove required file questionnaire
- title: fixing: remove required file questionnaire

fixing: remove required file questionnaire

---

src/modules/villages/village_rules.ts

- fixing: update rule questionnaire
- title: fixing: update rule questionnaire
- participants: @ayocodingit @indraprasetya154

fixing: update rule questionnaire

---

src/database/migrations/20211008031514_create_table_categories.ts
src/database/migrations/20211008032602_create_table_partners.ts
src/database/migrations/20211008033154_create_table_areas.ts
src/database/migrations/20211008033500_create_table_cities.ts
src/database/migrations/20211008033943_create_table_districts.ts
src/database/migrations/20211008034146_create_table_villages.ts
src/database/migrations/20211016232523_create_table_testimonials.ts
src/database/migrations/20211018084932_create_table_users.ts
src/database/migrations/20211105021056_create_table_oauth_tokens.ts
src/database/migrations/20211221034605_create_table_pages.ts
src/database/migrations/20211221035316_create_table_files.ts

- refactor migrations easy to read
- title: refactor migrations easy to read
- participants: @ayocodingit @sandisunandar99 @fajarhikmal214

refactor migrations easy to read

---

src/helpers/polygon.ts
src/modules/auth/auth_entity.ts
src/modules/auth/auth_handler.ts
src/modules/auth/auth_repository.ts
src/modules/cities/city_entity.ts
src/modules/cities/city_repository.ts
src/modules/cities/city_test.ts
src/modules/districts/district_entity.ts
src/modules/districts/district_repository.ts
src/modules/districts/district_test.ts
src/modules/pages/page_entity.ts
src/modules/pages/page_repository.ts
src/modules/partners/partner_entity.ts
src/modules/partners/partner_repository.ts
src/modules/partners/partner_test.ts
src/modules/testimonials/testimonial_entity.ts
src/modules/testimonials/testimonial_repository.ts
src/modules/users/user_entity.ts
src/modules/users/user_repository.ts
src/modules/villages/village_entity.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_test.ts

refactor all modules entity

---

src/helpers/polygon.ts
src/modules/cities/city_service.ts
src/modules/districts/district_service.ts
src/modules/villages/village_service.ts

- refactor: add helpers is request bounds 
- title: refactor: add helpers is request bounds
- participants: @ayocodingit @indraprasetya154 @rachadiannovansyah

refactor: add helpers is request bounds

---

src/modules/villages/village_rules.ts

- feat: update rule 3 about ecommerce
- title: feat: update rule 3 about ecommerce

feat: update rule 3 about ecommerce

---

src/modules/villages/village_rules.ts

- refactor: rule questionnaire
cc : @jabardigitalservice/jds-backend 
- title: refactor: rule questionnaire
- participants: @ayocodingit @sandisunandar99 @imamdev93 @rachadiannovansyah @indraprasetya154

refactor: rule questionnaire

---

src/modules/cities/city_entity.ts
src/modules/cities/city_handler.ts
src/modules/cities/city_http.ts
src/modules/cities/city_repository.ts
src/modules/cities/city_service.ts
src/modules/cities/city_test.ts

-  feat: add endpoint suggestion for city
- add endpoint suggestion for district
- title: feat: add endpoint suggestion for city
- participants: @ayocodingit @fajarhikmal214

feat: add endpoint suggestion city

---

src/modules/cities/city_test.ts
src/modules/districts/district_entity.ts
src/modules/districts/district_handler.ts
src/modules/districts/district_http.ts
src/modules/districts/district_repository.ts
src/modules/districts/district_service.ts
src/modules/districts/district_test.ts

- feat: add endpoint suggestion (districts)
- title: feat: add endpoint suggestion (districts)
- participants: @ayocodingit @rindibudiaramdhan

feat: add endpoint suggestion (districts)

---

src/modules/villages/village_rules.ts
src/modules/villages/village_test.ts

- feat: add field pemohon questionnaire
- title: feat: add field pemohon questionnaire
- participants: @ayocodingit @rachadiannovansyah

feat: add field pemohon questionnaire

---

src/helpers/cloudStorage.ts
src/modules/pages/page_service.ts
src/modules/pages/page_test.ts
src/modules/partners/partner_entity.ts
src/modules/partners/partner_repository.ts
src/modules/partners/partner_service.ts
src/modules/partners/partner_test.ts
src/modules/testimonials/testimonial_service.ts
src/modules/testimonials/testimonial_test.ts
src/modules/users/user_service.ts
src/modules/users/user_test.ts

- feat: update response logo (partners)
- title: feat: update response logo (partners)

feat: update response logo (partners)

---

.github/workflows/CI.yml
src/config/cache.ts
src/database/migrations/20220519043905_create_table_village_categories.ts

- feat: add table village categories
- feat: update field level in table categories
- update appendKey for cache
- title: feat: add table village categories
- participants: @ayocodingit @samudra-ajri

feat: add table village categories

---

src/modules/auth/auth_service.ts

- update: response avatar
- title: update: response avatar
- participants: @ayocodingit @samudra-ajri @rachadiannovansyah @fajarhikmal214 @sandisunandar99

update: response avatar

---

.github/workflows/dedi-service-release-staging.yml
.github/workflows/dedi-service-release-tags.yml

- setup argoCD
- title: CI/CD: setup argoCD
- participants: @ayocodingit @feriahmad

setup argoCD

---

src/modules/files/file_handler.ts
src/modules/files/file_http.ts

- feat: add endpoint download file
- title: feat: add endpoint download file
- participants: @ayocodingit

feat: add endpoint download file

---

.github/workflows/dedi-service-release-staging.yml
.github/workflows/dedi-service-release-tags.yml
src/database/migrations/20211105021056_create_table_oauth_tokens.ts

- fix: fixing length access token and refresh token

fix: fixing length access token and refresh token

---

src/modules/villages/village_repository.ts
src/modules/villages/village_rules.ts

- fix: add field updated at questionnaire
- title: fix: add field updated at questionnaire

fix: add field updated at questionnaire

---

src/database/migrations/20211008032602_create_table_partners.ts
src/modules/partners/partner_entity.ts
src/modules/partners/partner_repository.ts
src/modules/partners/partner_service.ts
src/modules/partners/partner_test.ts

- feat: add field join year
- title: feat: add field join year

feat: add field join year

---

src/config/cache.ts

- config: update redis cache duration
- title: config: update redis cache duration
- participants: @ayocodingit @sandisunandar99 @samudra-ajri

config: update redis cache duration

---

src/modules/auth/auth_repository.ts

- hotfix: set await when create partner
- title: hotfix: set await when create partner
- participants: @ayocodingit @sandisunandar99 @imamdev93

hotfix: set await when create partner

---

.eslintrc.json
.github/workflows/CI.yml
.github/workflows/dedi-service-release-staging.yml
.github/workflows/dedi-service-release-tags.yml
.prettierignore
jest.config.ts
src/config/cors.ts
src/config/index.ts
src/helpers/paginate.ts
src/helpers/regex.ts
src/helpers/upload.ts
src/helpers/validator.ts
src/lang/locales/id.json
src/modules/auth/auth_rules.ts
src/modules/pages/page_rules.ts
src/modules/testimonials/testimonial_rules.ts
src/modules/testimonials/testimonial_test.ts
src/modules/users/user_rules.ts
src/modules/villages/village_rules.ts
tsconfig.json

- set regex each type string 
- set interface cors options
- set request value with data validated
- [prettier other src](https://github.com/jabardigitalservice/dedi-core-service/pull/168/commits/cddaac94fd2e6124f656be4b13c324d756bee912)
- title: Add security validation for Threat Script Injection
- participants: @ayocodingit @imamdev93 @azophy @sandisunandar99 @rachadiannovansyah

bugfix: add string regex for validation

---

src/modules/users/user_access.ts
src/modules/users/user_entity.ts
src/modules/users/user_handler.ts
src/modules/users/user_http.ts
src/modules/users/user_log.ts
src/modules/users/user_repository.ts
src/modules/users/user_rules.ts
src/modules/users/user_service.ts
src/modules/users/user_test.ts

- refactor: modify method to class (Users)
- title : refactor: modify method to class (Users)
- participants: @ayocodingit

refactor: modify method to class (Users)

---

src/modules/villages/village_rules.ts
src/modules/villages/village_test.ts

- fix: update rule questionnaire vehicles
- title: fix: update rule questionnaire vehicles
- participants: @ayocodingit @rachadiannovansyah

fix: update rule questionnaire vehicles

---

src/modules/cities/city_access.ts
src/modules/cities/city_entity.ts
src/modules/cities/city_handler.ts
src/modules/cities/city_http.ts
src/modules/cities/city_repository.ts
src/modules/cities/city_rules.ts
src/modules/cities/city_service.ts
src/modules/villages/village_test.ts

- refactor: modify method to class (Cities)
- consistency of class name and namespace
- to make it easier to test unit tests
- more reusable
- title: refactor: modify method to class (Cities)

refactor: modify method to class (Cities)

---

src/config/cache.ts
src/database/migrations/20220625031838_add_index_field_verified_at_on_table_partners.ts
src/modules/partners/partner_entity.ts
src/modules/partners/partner_http.ts
src/modules/partners/partner_repository.ts
src/modules/partners/partner_rules.ts
src/modules/partners/partner_service.ts
src/modules/partners/partner_test.ts
src/modules/villages/village_repository.ts

- fix: bussines logic partner village after softlaunching
- title: fix: bussines logic partner village after softlaunching
- participants: @ayocodingit @rachadiannovansyah @azophy @indraprasetya154 @sandisunandar99 
- date: 2022-06-27

fix: partner village after softlaunching

---

src/helpers/regex.ts

- feat: update helpers regex simbol ! @ $ _ & *
- title: feat: update helpers regex simbol ! @ $ _ & *

feat: update helpers regex simbol ! @ $ _ & *

---

src/helpers/validator.ts
src/modules/auth/auth_rules.ts
src/modules/cities/city_repository.ts
src/modules/districts/district_repository.ts
src/modules/pages/page_repository.ts
src/modules/pages/page_rules.ts
src/modules/partners/partner_repository.ts
src/modules/testimonials/testimonial_entity.ts
src/modules/testimonials/testimonial_repository.ts
src/modules/testimonials/testimonial_rules.ts
src/modules/testimonials/testimonial_test.ts
src/modules/users/user_repository.ts
src/modules/users/user_rules.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_rules.ts
src/modules/villages/village_test.ts

- [feat: add rule trim](https://github.com/jabardigitalservice/dedi-core-service/commit/a6c6828b43f0c5c501d064124bb558d5d86f2b30)
- [feat: convert is_active boolean](https://github.com/jabardigitalservice/dedi-core-service/commit/3f28c7bd9fcf596b85e42f2c7680077284ee5928)
- title: feat: add rule trim
- participants: @ayocodingit

feat: add rule trim

---

src/config/cloudStorage.ts
src/helpers/constant.ts
src/helpers/upload.ts

- bugfix upload file multer issue
- title: bugfix upload file multer issue
- participants: @ayocodingit @azophy @sandisunandar99 @rachadiannovansyah @rindibudiaramdhan

bugfix upload file multer issue

---

src/config/index.ts
src/helpers/upload.ts

- fixing: upload file max 10 mb
- title: fixing: upload file max 10 mb
- participants: @ayocodingit @samudra-ajri @indraprasetya154 @rachadiannovansyah

fixing: upload file max 10 mb

---

src/modules/villages/village_service.ts
src/modules/villages/village_test.ts

- feat: remove condition level on checkRegistered
- title: feat: remove condition level 4 on checkRegistered
- participants: @ayocodingit @samudra-ajri @rachadiannovansyah @indraprasetya154 @sandisunandar99

feat: remove condition level 4 on checkRegistered

---

src/modules/auth/auth_entity.ts
src/modules/auth/auth_repository.ts
src/modules/auth/auth_service.ts
src/modules/cities/city_entity.ts
src/modules/cities/city_repository.ts
src/modules/districts/district_entity.ts
src/modules/districts/district_repository.ts
src/modules/pages/page_entity.ts
src/modules/pages/page_repository.ts
src/modules/partners/partner_entity.ts
src/modules/partners/partner_repository.ts
src/modules/testimonials/testimonial_entity.ts
src/modules/testimonials/testimonial_repository.ts
src/modules/users/user_entity.ts
src/modules/users/user_repository.ts
src/modules/villages/village_entity.ts
src/modules/villages/village_repository.ts

- chore: remove all name struct model
- title: chore: remove all name struct model
- participants: @ayocodingit @rindibudiaramdhan @samudra-ajri @indraprasetya154 @rachadiannovansyah @sandisunandar99

chore: remove all name struct model

---

src/helpers/regex.ts

- feat: update regex ext file case insensitive
- title: feat: update regex ext file case insensitive
- participants: @ayocodingit @tukangremot @imamdev93

feat: update regex ext file case insensitive

---

src/modules/auth/auth_log.ts
src/modules/partners/partner_log.ts
src/modules/testimonials/testimonial_log.ts
src/modules/villages/village_log.ts

- chore: update logger information service
- title: chore: update logger information service
- participants: @ayocodingit @samudra-ajri @indraprasetya154 @imamdev93 @rachadiannovansyah

chore: update logger information service

---

README.md
src/modules/cities/city_response.ts
src/modules/cities/city_service.ts
src/modules/districts/district_entity.ts
src/modules/districts/district_handler.ts
src/modules/districts/district_repository.ts
src/modules/districts/district_response.ts
src/modules/districts/district_service.ts
src/modules/pages/page_response.ts
src/modules/pages/page_service.ts
src/modules/partners/partner_response.ts
src/modules/partners/partner_service.ts
src/modules/testimonials/testimonial_response.ts
src/modules/testimonials/testimonial_service.ts
src/modules/users/user_response.ts
src/modules/users/user_service.ts
src/modules/villages/village_response.ts
src/modules/villages/village_service.ts

- chore: move mapping response on services
- title: move mapping response on services
- participants: @ayocodingit @sandisunandar99 @imamdev93 @rachadiannovansyah

chore: separate response

---

src/modules/villages/village_entity.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_response.ts
src/modules/villages/village_test.ts

- enhancement: add field district on list village
- title: enhancement: add field district on list village
- participants: @ayocodingit @rachadiannovansyah @rindibudiaramdhan

enhancement: add field district on list village

---

src/database/migrations/20220809055953_add_field_created_at_on_table_villages.ts
src/helpers/regex.ts
src/modules/villages/village_access.ts
src/modules/villages/village_entity.ts
src/modules/villages/village_handler.ts
src/modules/villages/village_http.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_rules.ts
src/modules/villages/village_service.ts
src/modules/villages/village_test.ts

- Feat: Add endpoint store village
- title: Feat: Add endpoint store village
- participants: @ayocodingit @rindibudiaramdhan @sandisunandar99 @indraprasetya154 @rachadiannovansyah

Feat: Add endpoint store village

---

src/modules/villages/village_access.ts
src/modules/villages/village_entity.ts
src/modules/villages/village_handler.ts
src/modules/villages/village_http.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_response.ts
src/modules/villages/village_rules.ts
src/modules/villages/village_service.ts
src/modules/villages/village_test.ts

- feat: add endpoint update (village)
- [update: response find by id](https://github.com/jabardigitalservice/dedi-core-service/pull/190/commits/5f266eea356c30ee00075ff827a47911d768d9f7)
- https://app.clickup.com/t/2qetrt3 
- title: feat: add endpoint update (village)
- participants: @ayocodingit @muhamadabduh @rachadiannovansyah

feat: add endpoint update (village)

---

src/modules/villages/village_entity.ts
src/modules/villages/village_http.ts
src/modules/villages/village_repository.ts
src/modules/villages/village_rules.ts

- feat: add sorting list with location (villages)
- https://app.clickup.com/t/2qetp5z
- title: feat: add sorting list with location (villages)
- participants: @ayocodingit @sandisunandar99 @azophy @imamdev93 @muhamadabduh @rindibudiaramdhan

feat: add sorting list with location (villages)

---

src/modules/users/user_entity.ts
src/modules/users/user_repository.ts
src/modules/users/user_response.ts
src/modules/users/user_rules.ts
src/modules/users/user_test.ts

- feat: add filter by partners (users)
- https://app.clickup.com/t/2qmjmb9
- title: feat: add filter by partners (users)
- participants: @ayocodingit @rhmnmbr83 @rindibudiaramdhan @rachadiannovansyah

feat: add filter by partners (users)

---

src/database/migrations/20220818072908_add_field_status_partner_on_table_users.ts
src/helpers/constant.ts
src/modules/auth/auth_entity.ts
src/modules/auth/auth_service.ts
src/modules/users/user_entity.ts
src/modules/users/user_repository.ts
src/modules/users/user_rules.ts
src/modules/users/user_service.ts

- feature: add field status partner (users)
- https://app.clickup.com/t/2qmjmb9
- Run Migration
- Exec Query
```sql
UPDATE users 
SET status_partner = "Menunggu Verifikasi" 
WHERE partner_id IS NOT NULL
```
- title: feature: add field status partner (users)
- participants: @ayocodingit @azophy @rindibudiaramdhan @sandisunandar99

feature: add field status partner (users)

---

src/modules/users/user_rules.ts
src/modules/users/user_service.ts

- enhancement: set status partner verified flow invitation (users)
- https://app.clickup.com/t/2qmjmcc
-
- Title: enhancement: set status partner verified flow invitation (users)
- Participants: @ayocodingit @rhmnmbr83 @imamdev93 @rindibudiaramdhan @sandisunandar99  @indraprasetya154

enhancement: set status partner verified flow invitation (users)

---

src/modules/auth/auth_repository.ts
src/modules/auth/auth_service.ts

- enhancement: update after sign in (Users)
- https://app.clickup.com/t/2qmjmcc
-
- Title: enhancement: update after sign in (Users)
- Participants: @ayocodingit @sandisunandar99 @rindibudiaramdhan @rachadiannovansyah @azophy

enhancement: update after sign in (Users)

---

src/modules/auth/auth_repository.ts

- chore: remove deleted at on method partner not exist (auth)
- consistent query select partner follow logic module users
- 
-
- Title: chore: remove deleted at on method partner not exist (auth)
- Participants: @ayocodingit @sandisunandar99 @indraprasetya154  @rachadiannovansyah @rindibudiaramdhan

chore: remove deleted at on method partner not exist (auth)

---

src/helpers/constant.ts
src/modules/auth/auth_entity.ts
src/modules/auth/auth_repository.ts

- bugfix: fix error method updateStatus (auth)
- update redaction lang indonesian nonaktif, ref: https://kbbi.lektur.id/nonaktif 
-
-
- Title: bugfix: fix error method updateStatus (auth)
- Participants: @ayocodingit @rachadiannovansyah @indraprasetya154 @rhmnmbr83

bugfix: fix error method updateStatus (auth)

---

src/modules/users/user_entity.ts
src/modules/users/user_service.ts
src/modules/users/user_test.ts

- feat: adjust update status partner (users)
- https://app.clickup.com/t/2qmjmn1
-
- Title: feat: adjust update status partner (users)
- Participants: @ayocodingit @azophy @rhmnmbr83

feat: adjust update status partner (users)

---

src/database/migrations/20220822085453_add_field_notes_on_table_users.ts
src/lang/locales/id.json
src/modules/auth/auth_entity.ts
src/modules/users/user_access.ts
src/modules/users/user_entity.ts
src/modules/users/user_handler.ts
src/modules/users/user_http.ts
src/modules/users/user_repository.ts
src/modules/users/user_rules.ts
src/modules/users/user_service.ts
src/modules/users/user_test.ts

- feat: add endpoint verify partner (users)
- feat: send mail 
- https://app.clickup.com/t/2qmjmnz
- Run Migrate
- Title: feat: add endpoint verify partner (users)
- Participants: @ayocodingit @rindibudiaramdhan @sandisunandar99 @rachadiannovansyah

feat: add endpoint verify partner (users)

---

src/lang/locales/id.json

- validation: add validation any unknown
- 
-
- Title: validation: add validation any unknown
- Participants: @ayocodingit @azophy @sandisunandar99 @rachadiannovansyah

validation: add validation any unknown

---

src/helpers/polygon.ts
src/helpers/regex.ts
src/modules/villages/village_test.ts

-  chore: regex point bounds move to regex (villages)
-
-
- Title: chore: regex point bounds move to regex (villages)
- Participants: @ayocodingit @rindibudiaramdhan @indraprasetya154 @rachadiannovansyah @azophy

chore: regex point bounds move to regex

---

src/helpers/templateEmail.ts
src/lang/locales/id.json
src/modules/users/user_handler.ts
src/modules/users/user_rules.ts
src/modules/users/user_service.ts
src/modules/users/user_test.ts

- feat: changes flow store user partner (Users)
- https://app.clickup.com/t/2qmjmcc
-
- Title: feat: changes flow store user partner (Users)
- Participants: @ayocodingit @rachadiannovansyah

feat: changes flow store user partner (Users)

---

src/modules/villages/village_repository.ts

- change: position long lat insert
-
- 
- https://stackoverflow.com/questions/23509690/how-to-convert-point-text-to-geometry
- https://postgis.net/docs/ST_MakePoint.html
- Title: change: position long lat insert
- Participants: @ayocodingit @azophy @sandisunandar99 @rachadiannovansyah @rhmnmbr83 @imamdev93

change: position long lat insert

---

src/modules/auth/auth_repository.ts
src/modules/auth/auth_service.ts

- fix: sign up not create partner
-
-
- Title: fix: sign up not create partner
- Participants: @ayocodingit

fix: sign up not create partner

---

src/modules/users/user_repository.ts

- feat: update query delete users following remove data partner
-
-
- Title: feat: update query delete a related user on a partner
- Participants: @ayocodingit @sandisunandar99 @rachadiannovansyah @imamdev93

feat: update query delete a related user on a partner

---

src/modules/users/user_handler.ts
src/modules/users/user_repository.ts
src/modules/users/user_rules.ts
src/modules/users/user_service.ts
src/modules/users/user_test.ts

- Improvement: refactor validation unique field company (users)
- 
-
- Title: Improvement: refactor validation unique field company (users)
- Participants: @ayocodingit @rindibudiaramdhan @rachadiannovansyah @sandisunandar99

Improvement: refactor validation unique field company (users)

---

src/modules/auth/auth_service.ts
src/modules/users/user_repository.ts

- bugfix: case signin password is null (auth)
- 
- 
- Title: bugfix: case signin password is null (auth)
- Participants: @ayocodingit

bugfix: case signin password is null

---

README.md
src/emails/README.md

- documentation: add folder emails readme 
- Title: documentation: add folder emails readme 
- Participants: @ayocodingit @rindibudiaramdhan @sandisunandar99

documentation: add folder emails readme 

---

src/modules/users/user_service.ts

- fix: modify verify accepted template
- 
- Title: fix: modify verify accepted template
- Participants: @ayocodingit @rachadiannovansyah @imamdev93

fix: modify verify accepted template

---

src/helpers/constant.ts
src/lang/locales/id.json

- chore: refactor enum to object
-
-
- Title: chore: refactor enum to object (user status)
- Participants: @ayocodingit @sandisunandar99 @rhmnmbr83 @rindibudiaramdhan

chore: refactor enum to object (user status)

---

src/database/migrations/20220909084530_create_table_questionnaires.ts
src/modules/questionnaires/questionnaire_entity.ts
src/modules/questionnaires/questionnaire_handler.ts
src/modules/questionnaires/questionnaire_http.ts
src/modules/questionnaires/questionnaire_repository.ts
src/modules/questionnaires/questionnaire_rules.ts
src/modules/questionnaires/questionnaire_service.ts

- enhancement: create table questionnaire
-
- run migrate
- Title: enhancement: create table questionnaire
- Participants: @ayocodingit @rachadiannovansyah

enhancement: create table questionnaire

---

src/emails/invitation_partner.handlebars
src/emails/verify_accepted_partner.handlebars
src/emails/verify_rejected_partner.handlebars
src/modules/users/user_service.ts

- modify: set dynamic name emails
-
-
- Title: modify: set dynamic name emails
- Participants: @ayocodingit @rachadiannovansyah @sandisunandar99 @rindibudiaramdhan @imamdev93

modify: set dynamic name emails

---

src/database/migrations/20220913235953_add_field_is_verified_on_table_village_categories.ts
src/modules/questionnaires/questionnaire_entity.ts
src/modules/questionnaires/questionnaire_repository.ts
src/modules/questionnaires/questionnaire_response.ts
src/modules/questionnaires/questionnaire_service.ts
src/modules/questionnaires/questionnaire_test.ts

- feat: add filter level four (questionnaires)
- 
- Run migrate
- improve questionnaires for level 4
- Title: feat: add filter level four (questionnaires)
- Participants: @ayocodingit @rindibudiaramdhan

feat: add filter level four (questionnaires)

---

src/modules/questionnaires/questionnaire_entity.ts
src/modules/questionnaires/questionnaire_handler.ts
src/modules/questionnaires/questionnaire_http.ts
src/modules/questionnaires/questionnaire_repository.ts
src/modules/questionnaires/questionnaire_response.ts
src/modules/questionnaires/questionnaire_rules.ts
src/modules/questionnaires/questionnaire_service.ts
src/modules/questionnaires/questionnaire_test.ts

- feat: add endpoint find by id (questionnaires)
-
-
- Title: feat: add endpoint find by id (questionnaires)
- Participants: @ayocodingit @sandisunandar99 @rachadiannovansyah

feat: add endpoint find by id (questionnaires)

---

src/modules/questionnaires/questionnaire_handler.ts
src/modules/questionnaires/questionnaire_service.ts
src/modules/questionnaires/questionnaire_test.ts

- feat: handle for not found find by id (questionnaire)
-
-
- Title: feat: handle for not found find by id (questionnaire)
- Participants: @ayocodingit @muhamadabduh @rachadiannovansyah

feat: handle for not found find by id (questionnaire)

---

src/modules/questionnaires/questionnaire_rules.ts

- chore: add rule validation unique village
-
-
- Title: chore: add rule validation unique village
- Participants: @ayocodingit @rindibudiaramdhan @rachadiannovansyah @indraprasetya154

chore: add rule validation unique village

---

src/modules/questionnaires/questionnaire_rules.ts
src/modules/questionnaires/questionnaire_test.ts

- chore: improve lang variable (questionnaires)
-
-
- Title: chore: improve lang variable (questionnaires)
- Participants: @ayocodingit @rachadiannovansyah @imamdev93

chore: improve lang variable (questionnaires)

---

src/modules/questionnaires/questionnaire_test.ts

- fix: api test (questionnaires)
-
-
- Title: fix: api test (questionnaires)
- Participants: @ayocodingit @rindibudiaramdhan @rachadiannovansyah

fix: api test (questionnaires)

---

src/modules/questionnaires/questionnaire_rules.ts
src/modules/users/user_service.ts

- [chore: add condition other potency](https://github.com/jabardigitalservice/dedi-core-service/commit/c4bda88dfe674a76913c017f448647c1cbd51017)
- [fix: send email verify](https://github.com/jabardigitalservice/dedi-core-service/commit/3e030b0c7b1f9717f0f43f8d6ab4335ebac2562a)
-
-
- Title: chore: add condition other potency (questionnaire)
- Participants: @ayocodingit @rachadiannovansyah

chore: add condition other potency (questionnaire)

---

.dockerignore
src/helpers/constant.ts
src/lang/locales/id.json
src/modules/questionnaires/questionnaire_entity.ts
src/modules/questionnaires/questionnaire_repository.ts
src/modules/questionnaires/questionnaire_rules.ts
src/modules/questionnaires/questionnaire_service.ts
src/modules/questionnaires/questionnaire_test.ts
src/modules/users/user_test.ts

- feat: store level 4 (questionnaires)
-
- 
- Title: feat: store level 4 (questionnaires)
- Participants: @ayocodingit @sandisunandar99 @rachadiannovansyah

feat: store level 4 (questionnaires)

---

src/modules/questionnaires/questionnaire_repository.ts

- Fix: Conditional list is level four
-
-
- Title: Fix: Conditional list is level four
- Participants: @ayocodingit

Fix: Conditional list is level four

---

src/modules/users/user_test.ts

- fix: api test (users) 
-
-
- Title: fix: api test (users) 
- Participants: @ayocodingit @rachadiannovansyah @rhmnmbr83 @imamdev93

fix: api test (users)
